name: Work

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@185.220.204.196
      DEPLOY_DIRECTORY: /root/apps/todoAPI

    steps:
      - name: Checkout rep
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Build
        run: |
          go mod download
          go build -o todoAPI ./cmd/todo

      - name: Deploy
        run: |
          sudo apt-get install -y ssh rsync 
          ssh {{ env.HOST }}
